### ISSUE TITLE
Allow for ID highlighting without triggering hyperlink

### ISSUE THREAD

**Issue by bhonick** [sennetconsortium/portal-ui#600]
In the HuBMAP Data Portal, I am able to highlight a HuBMAP ID without triggering the hyperlink. The gif below shows what I mean:

![Peek 2023-05-24 12-11](https://github.com/sennetconsortium/portal-ui/assets/71984404/cffc4f3c-54ff-4e6f-990c-086b9b35aaa1)

In the SenNet Data Portal, attempting to highlight a SenNet ID triggers the hyperlink. The gif below demonstrates this: 

![Peek 2023-05-24 12-13](https://github.com/sennetconsortium/portal-ui/assets/71984404/90a13547-6186-4ae3-85f8-da9a2e86078c)

I would like for this feature from the HuBMAP Data Portal to be replicated in the SenNet one. Thanks!

**Comment by libpitt** [comment]
@maxsibilla  For this one here, notice HuBMAP's row is not clickable, just the id. Do we want to match that, or keep our current functionality but add some listeners to detect highlighting (might get a little complicated)?

I am assuming the highlighting is in order to copy the id? Do we want to add the little clipboard copy functionality on it like in the view pages?

**Comment by maxsibilla** [comment]
@bhonick We will add a copy ID button in the results similar to what you see on entity landing pages:
<img width="451" alt="image" src="https://github.com/sennetconsortium/portal-ui/assets/7218802/4ab78ef4-cc2a-434b-a9e3-78cfa179e94f">
