### ISSUE TITLE
Add support for CCF Exploration tool

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#908]
While we support registering blocks using the CCF RUI tool we should look into if we can support the CCF exploration tool (https://portal.hubmapconsortium.org/ccf-eui). This would be integrated into card #907

**Comment by tjmadonna** [comment]
Basic integration has been added to the linked branch that uses static (but real) data. Waiting on `ccf-api` to fully integrate.

**Comment by tjmadonna** [comment]
I ran into issues loading images in `ccf-eui` in the portal. Documentation shows setting the `<base href="">` in the `<head>` to `https://cdn.jsdelivr.net/gh/hubmapconsortium/ccf-ui@3.7`. This is possible for an individual page in NextJS but breaks some of the other images on the page, such as the SenNet logo. The page tries to the load the logo from the cdn site.

A fix for this is to commit and serve the images from the portal. I have not committed the images yet as I wanted to look for another solution. Images can be found in the `ccf-ui` release.

**Comment by bherr2** [comment]
A couple of comments:

- Can you make the branch a draft PR so I can comment on specific lines of code?
- https://github.com/sennetconsortium/portal-ui/compare/tjmadonna/908-ccf-exploration-tool#diff-885c66a349aeb6834e24e7065559922ca911df47601a1bd445a4ea7a052af7faR10 <-- the new URL to use is <https://apps.humanatlas.io/hra-api/v1/sennet/rui_locations.jsonld>
- https://github.com/sennetconsortium/portal-ui/compare/tjmadonna/908-ccf-exploration-tool#diff-885c66a349aeb6834e24e7065559922ca911df47601a1bd445a4ea7a052af7faR30 <-- I'd recommend setting the version to @3 instead of @3.7 -- the latest 3.x release should be best (until 4.0 next year)
- There are some references functions with "RUI" in it that should probably be changed to EUI (or made more generic)

Otherwise looks pretty good. Let me know if you are having any issues.

One I know you'll see is that it's not super fast right now. There are some changes coming which should help that.

**Comment by maxsibilla** [comment]
@bherr2 Here is the draft PR for that https://github.com/sennetconsortium/portal-ui/pull/1073
