### ISSUE TITLE
Integrate Google analytics tracking for production only

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/portal-ui#95]

**Comment by libpitt** [comment]
Hello @maxsibilla, so Google Tag Manager (GTM) answers the question of what you mentioned yesterday in terms of the specificity of tracking. So when we want to track custom events etc., we add the library, then we get an exposed method `dataLayer.push` which takes an object where we can specify the values we want to pull into analytics. (Other configuration is required for capturing these parameters.)

Examples:
```
dataLayer.push({‘event’: ‘gtm.click’, ‘property’: ‘value’})
dataLayer.push({‘event’: ‘gtm.click’, ‘action’: ‘search’, ‘keywords’: ‘blood line’})
```
We can get granular and create our own event names from the GTM accounts management area:

`dataLayer.push({ ‘event’: ‘search’, ‘keywords’: ‘blood line’})`

Anyhow, the main thing I wanted to address was the implementation of sending these pushes.

1.	The regular React way is to use the onClick/onChange handlers. Then we can have a reusable function that makes calls to the dataLayer.push from GTM.

I’m not sure that's the best solution, I think there’ll be much repetition of handlers. 

2.	The other way since this is not concerned with state management, is to use a wrapper plugin to the `dataLayer.push `method, perhaps in the src/js directory and set attributes on the elements that need to be captured. E.g.
```
<button data-js-gtm=’search’>Search</button>

<form data-js-gtm=’facets’>
  …. 
</form>
```
The plugin can be written in an opinionated format, so there's less attribute definition on the elements or can be written in a very generic way... 

Let me know your thoughts ...

**Comment by maxsibilla** [comment]
I think the biggest hurdle moving forward will be integrating GTM with the elasticsearch library we utilize to create the home/search page called Search UI (https://docs.elastic.co/search-ui/overview). If you look at [search.js](https://github.com/sennetconsortium/portal-ui/blob/main/src/pages/search.js) you can see how we implement this library with the `SearchProvider` and `Layout` components. We also override the default facet buttons with our own custom [Facets.jsx](https://github.com/dbmi-pitt/search-ui/blob/d682c6509db840efe2c9c0c1ee727595d73fc5cb/components/core/Facets.jsx) and override the default search results table with [TableResults.jsx](https://github.com/sennetconsortium/portal-ui/blob/main/src/components/custom/TableResults.jsx).

I would say look to implement whichever of the two options you proposed into those components that is easier. If I were to guess, just placing a wrapper around certain elements like you suggested in option 2 will probably be the way to go. Let me know if you'd like to discuss more via Zoom

**Comment by libpitt** [comment]
Thanks @maxsibilla. This helps. Based on our case we'll have to be a little opinionated with the implementation. You can see that in js/ux/GoogleTagManager.js Easiest way with the Facets.jsx is to add the class `js-gtm--facets` and for the search form add `js-gtm--search` and so on... I just did facets and search for now. We can have a fallback to capture other elements. It's actually already working in a pre-alpha sense. https://github.com/sennetconsortium/portal-ui/tree/libpitt/google-tag-manager

**Comment by maxsibilla** [comment]
Looks good so far, I'd be interested to see how this reports the user interactions in the GTM console. 

Another note: feel free to create a branch in https://github.com/dbmi-pitt/search-ui (that is the submodule that the Facets component lives) with the same name so that we can keep those two repositories in sync with each other

**Comment by libpitt** [comment]
Thanks @maxsibilla. I can add you on the GA & GTM consoles. Tried using your work email but it is not registered with Gmail.  ...

In regards to the branch for search-ui. That leads me to another question:
Does pulling the updated changes into my branch for both the submodule `search-ui` or from the `main` branch create merging problems for the team at point of pull request ... ?
